# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to: str) -> str:
    """Say hello to `to`."""
    return f"Hello {to}!"

# Cell
# class NB2Bear():
#     def __init__(self):
#         pass

# Cell
# @patch
# def load_notebook(self, nb_fn: str) -> list:
#     """Load Jupyter notebook in Markdown format."""
#     nbc_out: str = os.popen(f"jupyter nbconvert --to markdown {nb_fn} --stdout").read()
#     nb_contents: list = nbc_out.splitlines()
#
#     return nb_contents