# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_runner.ipynb (unless otherwise specified).

__all__ = ['run_nb2bear']

# Cell
from .nb2bear import convert_nb_to_bear

import argparse

# Cell
def run_nb2bear():
    ap = argparse.ArgumentParser()
    ap.add_argument("-f", "--file", required=True, help="Path to Jupyter notebook")
    ap.add_argument("-t", "--token", required=True, help="Bear token")
    ap.add_argument("-l", "--layout", default="compact", const="compact", nargs="?", choices=("compact", "comfortable"),
                    help="Layout of Bear note")
    args = vars(ap.parse_args())
    convert_nb_to_bear(args["file"], args["token"], args["layout"])

# Cell
if __name__ == "__main__":
    run_nb2bear()